FROM node:18-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY ./package.json ./yarn.lock ./

RUN yarn install --pure-lockfile

COPY . ./

ARG HOST
ARG BASE_PATH
ARG NODE_ENV

CMD yarn dev
